language: ruby
cache: bundler
rvm:
  - 2.1.2
env:
  global:
    secure: AeHf5DhdtExNjXtV1nW8BFyP7Qh71Mx+t5+LCNMnItI07TQvoUhU1YbyCe6HeKK8e3S+ti/scYlzrCvrVesA4aPxp/FhiQ3LpscOKcjhq/hlHQfkzm0NKSFLVMOj6WZMfVRaWqaDgCVy59OGfJf89ZnfC0IYlaJgsOfhsSCELL0=
script:
  - RAILS_ENV=test bundle exec rake db:schema:load --trace
  - bundle exec rake db:test:prepare
  - bundle exec rake
before_script:
  - cp config/database.travis.yml config/database.yml
  - mysql -e 'create database staffnet2_test'
  - psql -c 'create database staffnet2_test' -U postgres